### ISSUE TITLE
Epicko ale napisy nie wycentrowane

### ISSUE THREAD

**Issue by 1p22geo** [Vladislavius17/Vladislavius17.github.io#1]
#### I tekst dziwny

**Comment by 1p22geo** [comment]
Trzeba tekst normalny a nie loremy same

**Comment by Vladislavius17** [comment]
ale tak się nazywają te filmy

**Comment by Vladislavius17** [comment]
lorem ipsum genesis

**Comment by 1p22geo** [comment]
Jak tam, nieroda sprawdził?

**Comment by 1p22geo** [comment]
Co powiedział?
Bo moim zdaniem to 6 murowane.
